language: go
dist: xenial
sudo: false
env:
    - GOARCH=amd64
go:
    - "1.6"
    - "1.7"
    - "1.8"
    - "1.9"
    - "1.10"
    - "1.11"
    - "1.12"
    - "1.13"
    - "1.14"
    - tip

addons:
    apt:
      packages:
         - libsamplerate0
         - libsamplerate0-dev
before_install:
    - go get github.com/mattn/goveralls
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci